### ISSUE TITLE
ビルドの最後に失敗

### ISSUE THREAD

**Issue by yesimanoob** [tobitti0/JoinLogoScpTrialSetLinux#4]
セットアップ方法通りにdocker-composeでビルド・インストールしましたが、`docker-compose up --build`の最後に下記のログが出ました：
```
Creating join_logo_scp_trial ... done
Attaching to join_logo_scp_trial
join_logo_scp_trial    |
join_logo_scp_trial    | > join_logo_scp_trial@1.0.0 start /join_logo_scp_trial
join_logo_scp_trial    | > node src/jlse.js "-i" "--help"
join_logo_scp_trial    |
join_logo_scp_trial    | internal/modules/cjs/loader.js:638
join_logo_scp_trial    |     throw err;
join_logo_scp_trial    |     ^
join_logo_scp_trial    |
join_logo_scp_trial    | Error: Cannot find module '/join_logo_scp_trial/src/jlse.js'
join_logo_scp_trial    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
join_logo_scp_trial    |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
join_logo_scp_trial    |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
join_logo_scp_trial    |     at startup (internal/bootstrap/node.js:283:19)
join_logo_scp_trial    |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
join_logo_scp_trial    | npm ERR! code ELIFECYCLE
join_logo_scp_trial    | npm ERR! errno 1
join_logo_scp_trial    | npm ERR! join_logo_scp_trial@1.0.0 start: `node src/jlse.js "-i" "--help"`
join_logo_scp_trial    | npm ERR! Exit status 1
join_logo_scp_trial    | npm ERR!
join_logo_scp_trial    | npm ERR! Failed at the join_logo_scp_trial@1.0.0 start script.
join_logo_scp_trial    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
join_logo_scp_trial    |
join_logo_scp_trial    | npm ERR! A complete log of this run can be found in:
join_logo_scp_trial    | npm ERR!     /root/.npm/_logs/2020-10-06T02_26_01_765Z-debug.log
join_logo_scp_trial exited with code 1
```

ホストにファイルはあるようです：
```
~/JoinLogoScpTrialSetLinux/modules/join_logo_scp_trial/src$ ls
channel.js  command  jlse.js  output  param.js  settings.js
```

どうすればいいでしょうか？

**Comment by tobitti0** [comment]
JoinLogoScpTrialSetLinux
の直下にsrc等の各フォルダやファイルがあるかをご確認いただけませんか。
というのも、modulesの中身はビルドに使用するだけで、稼働時はJoinLogoScpTrialSetLinux/srcなどのフォルダ類をコンテナ内にマウントしているのです。

**Comment by yesimanoob** [comment]
返信ありがとうございます。

コンテナ内に入っているようですが、何か間違ているのかしら？
```
:~/JoinLogoScpTrialSetLinux$ docker run -it --entrypoint /bin/bash feb44511d1af
root@321fa905af34:/join_logo_scp_trial# ls
 JL          bin    node_modules        package.json   setting   yarn.lock
 README.md   logo   package-lock.json   result         src      ''$'\350\252\254\346\230\216''.txt'
root@321fa905af34:/join_logo_scp_trial# ls src
channel.js  command  jlse.js  output  param.js  settings.js
```
コンテナ内から呼出すと正常に実行できるようです。
```
root@321fa905af34:/join_logo_scp_trial# node src/jlse.js -i --help
Options:
  --version      Show version number                                   [boolean]
  --input, -i    path to ts file                             [string] [required]
  --filter, -f   enable to ffmpeg filter output       [boolean] [default: false]
  --encode, -e   enable to ffmpeg encode              [boolean] [default: false]
  --target, -t   select encord target
                        [choices: "cutcm", "cutcm_logo"] [default: "cutcm_logo"]
  --option, -o   set ffmpeg option                        [string] [default: ""]
  --outdir, -d   set encorded file dir                    [string] [default: ""]
  --outname, -n  set encorded file name                   [string] [default: ""]
  --remove, -r   remove avs files                     [boolean] [default: false]
  --help         Show help                                             [boolean]
```

**Comment by yesimanoob** [comment]
docker-compose.ymlのvolume配列をコメントアウトすると、問題なく動作します。ということは、マウントするのは何らかの理由で失敗しています。こちらの環境問題かもしれません…

**Comment by tobitti0** [comment]
`docker run`だと、docker-compose.ymlに書いてあるマウントがされないので、内部にあるのは正常です。
`docker-compose up`した後に`docker exec` で入ると中には何もないのではないかと思います。
コンテナの中ではなく、docker-compose.ymlと同階層にsrcや、settingなどのフォルダと中身があるか確認してもらえますか？
```
git clone --recursive https://github.com/tobitti0/JoinLogoScpTrialSetLinux.git
cd JoinLogoScpTrialSetLinux
cp -r modules/join_logo_scp_trial/JL .
cp -r modules/join_logo_scp_trial/setting .
cp -r modules/join_logo_scp_trial/src .
docker-compose up --build
```
手順通りにやっているのであれば、cpの部分がdocker-compose.ymlと同階層にコピーさせてるはずではあるのですが。

**Comment by yesimanoob** [comment]
その通りですね。いろいろ拝見したところ、私は急いで間違ったフォルダーをコピーしてしまいました！申し訳ありませんでした。
似ていますが下記は間違ってコピーしたパスです。
```
cp -r modules/join_logo_scp/JL .
cp -r modules/join_logo_scp/setting .
cp -r modules/join_logo_scp/src .
```

気になりますが、どうしてコンテナ内部にあるsrcじゃなくて、ホスト側にあるsrcを実行するようにしましたか？JLやsettingをホストから引っ張るのは理解できますが素人の私にとってsrcは内部にあるこのを使うべきかと思いました。

**Comment by tobitti0** [comment]
似た名前のフォルダなのでコピペではなく手打ちした場合、確かに間違う可能性はありますね。
動作したようでよかったです。

ホストにあるsrcを実行する理由ですが、特に深い理由はないです。手軽に動作確認するのがDockerの目的と思うのでコンテナ内部のを実行するべきかもしれません。
実際はローカルに導入するか、EPGStationなどのDockerfileに組み込む運用になるのかなと考えていますので、添付しているDockerは単に動作確認用の意味合いが強いかなと思います。
ただ、settingやJLは動作に使うのでhelp表示できても実際に動かそうとすると何らかのエラーが出ることになると思います。そういう意味ではsrcがコピーできていればそれらもコピーできているということになるのかなと思ったりも。（今考えた後付けの理由ですが）

私自身`Docker-compose`への知識がまだ浅いのでホストで必要なファイルをコピーする形ですが、本来は初回時にコンテナ内部からホストへファイルをどうにかして出すのがベストではあると思います。時間があれば調べてみようと思います。それか、初回はシェルスクリプトを実行するように案内して、スクリプトでコピーするようにするかですかね。

**Comment by yesimanoob** [comment]
私はdocker-composeの初心者なので勉強のために聞いてみただけです。真面目に答えてくれてありがとうございました！
